apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 00_namespaces
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default
  project: default
  source:
    path: namespaces
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}

