spec:
  destination:
    server: https://E4F196DFD9368240885050B4C30E496D.gr7.eu-west-1.eks.amazonaws.com
    namespace: default
  source:
    repoURL: https://github.com/bennycornelissen/argocd-example-apps
    targetRevision: HEAD
